Added hint color
PixiEditor/ColorPicker pull request #31
Opened 2022-03-25 19:26 UTC by flabbet

Hint color is a small color box that selects primary color of dual picker to its value. Can be used as a reference to main color in PixiEditor. Examples in demo app.

Also I added some rounding to look, so it fits PixiEditor more

2022-03-26 08:08 UTC, Equbuxu requested changes
- I believe the .idea folder should be added to gitignore and removed from the commits
- It would be nice to make the rounded corners a part of the dark theme (which is what pixieditor uses) instead of forcing everyone to use them. Also, while you are at it, you can change the selection color, the textbox highlighted border color, and the textbox corners as well.
- The hint color button overlaps with the hue circle when scaling the control:
![image](https://user-images.githubusercontent.com/29402050/160230292-8e27d43a-be55-45bc-8e2d-57144443bf4e.png)
- The screenshots in readme need updating

2022-03-26 08:08 UTC, Equbuxu commented on src/ColorPicker/DualPickerControlBase.cs
> +            if (sender.ignoreSecondaryColorPropertyChange)
```suggestion
            if (sender.ignoreHintNotifyablePropertyChange)
```

2022-03-26 11:02 UTC, flabbet commented
Fixed all

2022-03-27 12:29 UTC, Equbuxu approved these changes

2022-03-27 16:45 UTC, merged